services:
    _defaults:
        autowire: true
        autoconfigure: true

    SensioLabs\Security\SecurityChecker: null

    SensioLabs\Security\Command\SecurityCheckerCommand:
        arguments: ['@SensioLabs\Security\SecurityChecker']
        public: false
        tags:
            - { name: console.command, command: 'security:check' }
