twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths: 
        '%kernel.project_dir%/assets/images-site': images
        '%kernel.project_dir%/assets/css': css
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
